# Generated by Django 4.2.20 on 2025-04-18 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_course_student_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
